update for more test

diff --git a/.github/workflows/ut_x86_default.yml b/.github/workflows/ut_x86_default.yml
--- a/.github/workflows/ut_x86_default.yml
+++ b/.github/workflows/ut_x86_default.yml
@@ -14,7 +14,8 @@ jobs:
     if: "!startsWith(github.event.head_commit.message, 'GitHubAction:')"
     strategy:
       matrix:
-          api-level: [ 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28, 29 ]
+          #api-level: [ 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28, 29 ]
+          api-level: [ 17 ]
           target: [default]
           arch: [x86]
     steps:
@@ -85,12 +86,13 @@ jobs:
             ls
             source ./replace_line.sh || true
             comment || true
+            # may failed
             ./gradlew connectedAndroidTest mergeAndroidReports || true
-            echo "==============run case over==============="
+            echo "==============run case over===============" || true
             tar -zcvf ut_${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}.tgz build/ dev-sdk/build/reports/>t.txt || true
-            echo "==============tar ut over. ls==============="
-            echo "${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }} 运行完毕。。。。。。。。。"
-            rm -rf ~/.android/avd/
+            echo "==============tar ut over. ls===============" || true
+            echo "${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }} 运行完毕。。。。。。。。。" || true
+            rm -rf ~/.android/avd/ || true
 
       - name: ypload
         shell: bash
